<a href="https://colab.research.google.com/github/muditkumar14/aiml/blob/main/Mudit_kumar_Singh_Assignment_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

data = np.array([[22.5, 19.0, 31.2, 28.7, 25.1],
                 [17.3, 22.8, 30.5, 26.4, 21.9],
                 [33.1, 29.6, 18.4, 24.0, 27.8],
                 [20.2, 23.5, 31.9, 28.1, 22.6]])


In [3]:
data.shape

(4, 5)

In [7]:
data[0].mean()

np.float64(25.259999999999998)

In [8]:
data[1].mean()

np.float64(23.78)

In [9]:
data[2].mean()

np.float64(26.580000000000002)

In [10]:
data[3].mean()

np.float64(25.259999999999998)

In [20]:
data>28

array([[False, False,  True,  True, False],
       [False, False,  True, False, False],
       [ True,  True, False, False, False],
       [False, False,  True,  True, False]])

In [21]:
data[data>28]

array([31.2, 28.7, 30.5, 33.1, 29.6, 31.9, 28.1])

In [24]:
normalized = ((data - data.min()) / (data.max() - data.min())).round(2)
normalized

array([[0.33, 0.11, 0.88, 0.72, 0.49],
       [0.  , 0.35, 0.84, 0.58, 0.29],
       [1.  , 0.78, 0.07, 0.42, 0.66],
       [0.18, 0.39, 0.92, 0.68, 0.34]])